spring:
  application:
    name: customer-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_info_db
    password: dumith
    username: dumith
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true